from agent_zoo.multi_agent_as_tools import analysing_orchestrator, analysing_orchestrator_w_regcheck
from agent_zoo.multi_agent_handoffs import analysing_orchestrator as analysing_orchestrator_handoffs, analysing_orchestrator_w_regcheck as analysing_orchestrator_w_regcheck_handoffs
from agent_zoo.multi_agent_with_orchestrator import orchestrator, orchestrator_w_regcheck
from agent_zoo.single_agent import single_agent, single_agent_w_regcheck
