import os
import sys
import subprocess

from loguru import logger
from pathlib import Path
from typing import List, Optional, Union, Dict

from agents import function_tool, RunContextWrapper

from brats import MissingMRI
from brats.constants import MissingMRIAlgorithms

from util.data_types import PatientInput, TargetRegions, Patient
from util.context_manager import SessionContext
from tools.register import register_one_image

CUDA_DEVICES = os.environ.get("CUDA_VISIBLE_DEVICES", "all")

name_mapping = {
    't1': 't1n',
    't2': 't2w',
    'flair': 't2f',
    't1c': 't1c'
}


@function_tool
def generate_missing_modality(wrapper: RunContextWrapper, patient_name: str) -> str:
    """
    Generate a missing MRI modality (t1, t2, flair, t1c) for a given patient using a pretrained model. 
    Any field that contains a "placeholder" value in the patient context will be considered as missing and will be generated by this tool.
    This tool will generate one modality at a time, so if multiple modalities are missing, it runs iteratively until all missing modalities are generated.
    Writes the result as a NIfTI file and updates the patient context with the generated modality.

    """
    if CUDA_DEVICES == "all":
        device = "0"
    else:
        device = CUDA_DEVICES.split(",")[0]  

    missing_mri_generator = MissingMRI(algorithm=MissingMRIAlgorithms.BraTS25_1, cuda_devices=device)

    patient = wrapper.context.get(patient_name)
    out_dir = wrapper.context.get("output_dir") / patient_name / 'preprocessed'
    out_dir.mkdir(parents=True, exist_ok=True)

    available_modalities = {modality: getattr(patient, modality) for modality in ['t1', 't2', 'flair', 't1c']}
    missing_modalities = {mod: path for mod, path in available_modalities.items() if "placeholder" in path.lower()}
    available_modalities = {name_mapping[mod]: path for mod, path in available_modalities.items() if "placeholder" not in path.lower()}

    if not missing_modalities:
        logger.info(f"No missing modalities found for patient {patient_name}.")
        return "No missing modalities to generate. Unnecessary tool call."

    generated = []
    for mod in missing_modalities:
        out_file = out_dir / f"{patient_name}_{mod}_generated.nii.gz"
        missing_mri_generator.infer_single(
            **available_modalities,
            output_path=str(out_file)
        )
        available_modalities[name_mapping[mod]] = str(out_file)
        setattr(patient, mod, str(out_file))
        generated.append(mod)

    wrapper.context.set(patient.name, patient)
    return f"Generated missing modalities in the specific order: {', '.join(generated)} for patient {patient_name} and updated the patient context accordingly."
